/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.main;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author ADMIN
 */


public class Login extends javax.swing.JFrame {
    private static HashMap<String, String> accounts = new HashMap<>();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        BrandName = new JLabel();
        CopyRight = new JLabel();
        logo = new JLabel();
        Right = new javax.swing.JPanel();
        LoginLabel = new JLabel();
        EmailLabel = new JLabel();
        EmailField = new javax.swing.JTextField();
        PasswordLabel = new JLabel();
        PasswordField = new javax.swing.JPasswordField();
        SignUpButtons = new javax.swing.JButton();
        jLabel4 = new JLabel();
        LoginButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        SignUp = new javax.swing.JPanel();
        Left2 = new javax.swing.JPanel();
        BrandName2 = new JLabel();
        CopyRight2 = new JLabel();
        logo1 = new JLabel();
        Right1 = new javax.swing.JPanel();
        SignUpLabel = new JLabel();
        Fullname = new JLabel();
        emailField = new javax.swing.JTextField();
        fullnameField = new javax.swing.JTextField();
        Email = new JLabel();
        Password = new JLabel();
        passwordField = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        jLabel5 = new JLabel();
        LoginButton1 = new javax.swing.JButton();
        ForgotPassword = new javax.swing.JPanel();
        pnContainer = new javax.swing.JPanel();
        pnTitle = new javax.swing.JPanel();
        lbl_quen_mat_khau = new JLabel();
        icon_quen_mat_khau = new JLabel();
        lbl_username = new JLabel();
        email_field = new javax.swing.JTextField();
        lbl_email = new JLabel();
        username_field = new javax.swing.JTextField();
        btn_xac_nhan = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new CardLayout());

        Login.setBackground(new Color(255, 255, 255));
        Login.setPreferredSize(new java.awt.Dimension(900, 500));
        Login.setLayout(null);

        Left.setBackground(new Color(204, 0, 0));
        Left.setPreferredSize(new java.awt.Dimension(400, 500));

        BrandName.setFont(new java.awt.Font("Showcard Gothic", 3, 36)); // NOI18N
        BrandName.setForeground(new Color(255, 255, 255));
        BrandName.setText("CLC04 Airlines");

        CopyRight.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        CopyRight.setForeground(new Color(255, 255, 255));
        CopyRight.setText("copyright (c) CLC04 AIRLINES All rights reversed");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CopyRight)
                    .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(93, 93, 93))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                            .addComponent(BrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)))))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(BrandName)
                .addGap(91, 91, 91)
                .addComponent(CopyRight)
                .addGap(106, 106, 106))
        );

        Login.add(Left);
        Left.setBounds(0, 0, 450, 500);

        Right.setBackground(new Color(255, 255, 255));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LoginLabel.setForeground(new Color(204, 0, 0));
        LoginLabel.setText("LOGIN");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        EmailLabel.setText("Email");

        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PasswordLabel.setText("Password");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        SignUpButtons.setBackground(new Color(204, 204, 204));
        SignUpButtons.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        SignUpButtons.setText("Sign Up");
        SignUpButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("I don't have a acccount");

        LoginButton.setBackground(new Color(204, 0, 0));
        LoginButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        LoginButton.setForeground(new Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton3.setForeground(new Color(255, 255, 255));
        jButton3.setText("Forgot Password");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                        .addComponent(LoginButton)
                        .addGap(90, 90, 90)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PasswordLabel)
                    .addComponent(EmailLabel)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(RightLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SignUpButtons))))
                .addGap(76, 76, 76))
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(LoginLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LoginLabel)
                .addGap(19, 19, 19)
                .addComponent(EmailLabel)
                .addGap(18, 18, 18)
                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SignUpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        Login.add(Right);
        Right.setBounds(450, 0, 450, 500);

        getContentPane().add(Login, "login");

        SignUp.setBackground(new Color(255, 255, 255));
        SignUp.setPreferredSize(new java.awt.Dimension(900, 500));
        SignUp.setLayout(null);

        Left2.setBackground(new Color(204, 0, 0));
        Left2.setPreferredSize(new java.awt.Dimension(400, 500));

        BrandName2.setFont(new java.awt.Font("Showcard Gothic", 3, 36)); // NOI18N
        BrandName2.setForeground(new Color(255, 255, 255));
        BrandName2.setText("CLC04 Airlines");

        CopyRight2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        CopyRight2.setForeground(new Color(255, 255, 255));
        CopyRight2.setText("copyright (c) CLC04 AIRLINES All rights reversed");

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout Left2Layout = new javax.swing.GroupLayout(Left2);
        Left2.setLayout(Left2Layout);
        Left2Layout.setHorizontalGroup(
            Left2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Left2Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(Left2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CopyRight2)
                    .addGroup(Left2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Left2Layout.createSequentialGroup()
                            .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(93, 93, 93))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Left2Layout.createSequentialGroup()
                            .addComponent(BrandName2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)))))
        );
        Left2Layout.setVerticalGroup(
            Left2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(BrandName2)
                .addGap(91, 91, 91)
                .addComponent(CopyRight2)
                .addGap(106, 106, 106))
        );

        SignUp.add(Left2);
        Left2.setBounds(0, 0, 450, 500);

        Right1.setBackground(new Color(255, 255, 255));

        SignUpLabel.setBackground(new Color(255, 255, 255));
        SignUpLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        SignUpLabel.setForeground(new Color(204, 0, 0));
        SignUpLabel.setText("SIGN UP");

        Fullname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Fullname.setText("Full name");

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        fullnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameFieldActionPerformed(evt);
            }
        });

        Email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Email.setText("Email");

        Password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Password.setText("Password");

        SignUpButton.setBackground(new Color(204, 0, 0));
        SignUpButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        SignUpButton.setForeground(new Color(255, 255, 255));
        SignUpButton.setText("Sign Up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("I've an account");

        LoginButton1.setBackground(new Color(204, 204, 204));
        LoginButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        LoginButton1.setText("Login");
        LoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Right1Layout = new javax.swing.GroupLayout(Right1);
        Right1.setLayout(Right1Layout);
        Right1Layout.setHorizontalGroup(
            Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Right1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(130, 130, 130)
                        .addComponent(LoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Fullname)
                    .addComponent(fullnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignUpLabel)
                .addGap(151, 151, 151))
        );
        Right1Layout.setVerticalGroup(
            Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(SignUpLabel)
                .addGap(18, 18, 18)
                .addComponent(Fullname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fullnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        SignUp.add(Right1);
        Right1.setBounds(450, 0, 450, 500);

        getContentPane().add(SignUp, "signup");

        ForgotPassword.setPreferredSize(new java.awt.Dimension(900, 500));

        pnContainer.setBackground(new Color(255, 255, 255));

        pnTitle.setBackground(new Color(204, 0, 0));

        lbl_quen_mat_khau.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lbl_quen_mat_khau.setForeground(new Color(255, 255, 255));
        lbl_quen_mat_khau.setText("QUÊN MẬT KHẨU");

        icon_quen_mat_khau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/forgotpassword.png"))); // NOI18N

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_quen_mat_khau, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_quen_mat_khau)
                .addGap(279, 279, 279))
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_quen_mat_khau)
                .addGap(26, 26, 26))
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbl_quen_mat_khau)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_username.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_username.setText("Nhập Username:");

        lbl_email.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_email.setText("Nhập Email đã đăng kí:");

        btn_xac_nhan.setBackground(new Color(204, 204, 204));
        btn_xac_nhan.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btn_xac_nhan.setText("Xác nhận");

        btn_huy.setBackground(new Color(204, 204, 204));
        btn_huy.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnContainerLayout = new javax.swing.GroupLayout(pnContainer);
        pnContainer.setLayout(pnContainerLayout);
        pnContainerLayout.setHorizontalGroup(
            pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnContainerLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_username)
                    .addComponent(lbl_email)
                    .addGroup(pnContainerLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_xac_nhan)))
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnContainerLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnContainerLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btn_huy)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        pnContainerLayout.setVerticalGroup(
            pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContainerLayout.createSequentialGroup()
                .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_username)
                    .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_email)
                    .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xac_nhan)
                    .addComponent(btn_huy))
                .addGap(0, 59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ForgotPasswordLayout = new javax.swing.GroupLayout(ForgotPassword);
        ForgotPassword.setLayout(ForgotPasswordLayout);
        ForgotPasswordLayout.setHorizontalGroup(
            ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ForgotPasswordLayout.setVerticalGroup(
            ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(ForgotPassword, "forgotpassword");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void SignUpButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonsActionPerformed
        showPanel("signup");
    }//GEN-LAST:event_SignUpButtonsActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String email = EmailField.getText();
        String password = new String(PasswordField.getPassword());
        
        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không được để trống thông tin!","Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
        else if(accounts.containsKey(email) && password.equals(accounts.get(email)))
        {
            new Login().dispose();
            Menu MenuFrame = new Menu();
            MenuFrame.setVisible(true);
            MenuFrame.pack();
            MenuFrame.setLocationRelativeTo(null);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Sai tài khoản hoặc mật khẩu!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void fullnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameFieldActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed

        String email = emailField.getText();
        String password = new String(passwordField.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không được để trống thông tin!","Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
        else if(accounts.containsKey(email))
        {
            JOptionPane.showMessageDialog(null, "Email đã tồn tại","Lỗi!", JOptionPane.ERROR_MESSAGE);

        }
        else {
            accounts.put(email,password);
            JOptionPane.showMessageDialog(null,"Đăng kí thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            emailField.setText("");
            passwordField.setText("");
            fullnameField.setText("");
        }   
            
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void LoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButton1ActionPerformed
        showPanel("login"); 
    }//GEN-LAST:event_LoginButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        showPanel("forgotpassword");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        showPanel("login");
    }//GEN-LAST:event_btn_huyActionPerformed

    
    
    private void showPanel(String panelName) {                                                
       CardLayout layout = (CardLayout) getContentPane().getLayout();
        layout.show(getContentPane(), panelName);
    }
   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login l = new Login();
                l.setVisible(true);
                l.pack();
                l.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel BrandName;
    private JLabel BrandName2;
    private JLabel CopyRight;
    private JLabel CopyRight2;
    private JLabel Email;
    private javax.swing.JTextField EmailField;
    private JLabel EmailLabel;
    private javax.swing.JPanel ForgotPassword;
    private JLabel Fullname;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Left2;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton LoginButton1;
    private JLabel LoginLabel;
    private JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private JLabel PasswordLabel;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel Right1;
    private javax.swing.JPanel SignUp;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JButton SignUpButtons;
    private JLabel SignUpLabel;
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_xac_nhan;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField email_field;
    private javax.swing.JTextField fullnameField;
    private JLabel icon_quen_mat_khau;
    private javax.swing.JButton jButton3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel lbl_email;
    private JLabel lbl_quen_mat_khau;
    private JLabel lbl_username;
    private JLabel logo;
    private JLabel logo1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnTitle;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
