/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.main;

import java.awt.List;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {
    
    int x = 300;    //chieu rong
    int y = 750;    //chieu cao

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        cardTrangChu.setVisible(true);
        
        jplSlideMenu.setSize(300,750);
    }

    public void openMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 0) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 0; i <= 300; i++) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(2);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 300;
        }
    }

    public void closeMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 300) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 300; i >= 0; i--) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(2);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mat_khau_field = new javax.swing.JTextField();
        pnContainer = new javax.swing.JPanel();
        thanh_menu = new javax.swing.JPanel();
        lbl_menu = new javax.swing.JLabel();
        jplSlideMenu = new javax.swing.JPanel();
        container_avatar_close = new javax.swing.JPanel();
        lblCloseMenu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblHoSo = new javax.swing.JLabel();
        lblTrangChu = new javax.swing.JLabel();
        lblDatVe = new javax.swing.JLabel();
        lblVeCuaToi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_dang_xuat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jplMain = new javax.swing.JPanel();
        cardTrangChu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cardDatVe = new javax.swing.JPanel();
        pnContainer1 = new javax.swing.JPanel();
        pn_tim_kiem_chuyen_bay = new javax.swing.JPanel();
        radiobutton_1_chieu = new javax.swing.JRadioButton();
        lbl_diem_den = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbl_diem_khoi_hanh = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lbl_so_luong_hanh_khach = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        lbl_ngay_bay = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btn_tim_chuyen_bay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btn_tiep_tuc = new javax.swing.JButton();
        cardVeCuaToi = new javax.swing.JPanel();
        pnContainer2 = new javax.swing.JPanel();
        pnTitle2 = new javax.swing.JPanel();
        lbl_ve_cua_toi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnTicket = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        pnTitle = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        pnBorder = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_passenger_name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_from = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_to = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_flight = new javax.swing.JLabel();
        lbl_board_till = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_to1 = new javax.swing.JLabel();
        lbl_seat = new javax.swing.JLabel();
        lbl_gate = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbl_gate1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lbl_from1 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lbl_passenger_name1 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        lbl_date1 = new javax.swing.JLabel();
        lbl_time1 = new javax.swing.JLabel();
        lbl_flight1 = new javax.swing.JLabel();
        lbl_seat1 = new javax.swing.JLabel();
        cardHoSo = new javax.swing.JPanel();
        pnContainer3 = new javax.swing.JPanel();
        pnTitle1 = new javax.swing.JPanel();
        lbl_ho_so = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_so_dien_thoai = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_cmnd = new javax.swing.JLabel();
        lbl_ho_va_ten = new javax.swing.JLabel();
        lbl_gioi_tinh = new javax.swing.JLabel();
        lbl_mat_khau = new javax.swing.JLabel();
        cmnd_field = new javax.swing.JTextField();
        ho_va_ten_field = new javax.swing.JTextField();
        so_dien_thoai_field = new javax.swing.JTextField();
        gioi_tinh_field = new javax.swing.JTextField();
        email_field = new javax.swing.JTextField();
        ten_dang_nhap_field = new javax.swing.JTextField();
        btn_doi_mat_khau = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        mat_khau_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat_khau_fieldActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnContainer.setPreferredSize(new java.awt.Dimension(1200, 800));
        pnContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        thanh_menu.setBackground(new java.awt.Color(255, 255, 255));

        lbl_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/menu.png"))); // NOI18N
        lbl_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout thanh_menuLayout = new javax.swing.GroupLayout(thanh_menu);
        thanh_menu.setLayout(thanh_menuLayout);
        thanh_menuLayout.setHorizontalGroup(
            thanh_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thanh_menuLayout.createSequentialGroup()
                .addComponent(lbl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1111, Short.MAX_VALUE))
        );
        thanh_menuLayout.setVerticalGroup(
            thanh_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_menu)
        );

        pnContainer.add(thanh_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        jplSlideMenu.setBackground(new java.awt.Color(255, 255, 255));
        jplSlideMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jplSlideMenu.setPreferredSize(new java.awt.Dimension(300, 750));

        container_avatar_close.setBackground(new java.awt.Color(255, 255, 255));
        container_avatar_close.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCloseMenu.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lblCloseMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseMenu.setText("X");
        lblCloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMenuMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/avatar.png"))); // NOI18N

        javax.swing.GroupLayout container_avatar_closeLayout = new javax.swing.GroupLayout(container_avatar_close);
        container_avatar_close.setLayout(container_avatar_closeLayout);
        container_avatar_closeLayout.setHorizontalGroup(
            container_avatar_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_avatar_closeLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        container_avatar_closeLayout.setVerticalGroup(
            container_avatar_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_avatar_closeLayout.createSequentialGroup()
                .addGroup(container_avatar_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        lblHoSo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblHoSo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoSo.setText("Hồ sơ");
        lblHoSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoSoMouseClicked(evt);
            }
        });

        lblTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        lblTrangChu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrangChu.setText("Trang Chủ");
        lblTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseClicked(evt);
            }
        });

        lblDatVe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDatVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatVe.setText("Đặt vé");
        lblDatVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDatVeMouseClicked(evt);
            }
        });

        lblVeCuaToi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblVeCuaToi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVeCuaToi.setText("Vé của tôi");
        lblVeCuaToi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVeCuaToiMouseClicked(evt);
            }
        });

        label_dang_xuat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_dang_xuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_dang_xuat.setText("Đăng Xuất");
        label_dang_xuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_dang_xuatMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Giới Thiệu");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Trợ Giúp");

        javax.swing.GroupLayout jplSlideMenuLayout = new javax.swing.GroupLayout(jplSlideMenu);
        jplSlideMenu.setLayout(jplSlideMenuLayout);
        jplSlideMenuLayout.setHorizontalGroup(
            jplSlideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container_avatar_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblDatVe, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblVeCuaToi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(label_dang_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jplSlideMenuLayout.setVerticalGroup(
            jplSlideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplSlideMenuLayout.createSequentialGroup()
                .addComponent(container_avatar_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblDatVe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblVeCuaToi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_dang_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pnContainer.add(jplSlideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 0, -1));

        jplMain.setBackground(new java.awt.Color(255, 255, 255));
        jplMain.setPreferredSize(new java.awt.Dimension(1200, 750));
        jplMain.setLayout(new java.awt.CardLayout());

        cardTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        cardTrangChu.setPreferredSize(new java.awt.Dimension(1200, 750));
        cardTrangChu.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Chúc bạn có một chuyến bay vui vẻ !");
        cardTrangChu.add(jLabel4);
        jLabel4.setBounds(220, 150, 680, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/bg.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.setPreferredSize(new java.awt.Dimension(1200, 750));
        cardTrangChu.add(jLabel12);
        jLabel12.setBounds(0, 0, 1200, 750);

        jplMain.add(cardTrangChu, "card2");

        cardDatVe.setPreferredSize(new java.awt.Dimension(1200, 750));

        pnContainer1.setBackground(new java.awt.Color(255, 255, 255));
        pnContainer1.setMinimumSize(new java.awt.Dimension(1200, 750));
        pnContainer1.setPreferredSize(new java.awt.Dimension(1200, 750));

        pn_tim_kiem_chuyen_bay.setBackground(new java.awt.Color(204, 0, 0));

        radiobutton_1_chieu.setBackground(new java.awt.Color(204, 0, 0));
        radiobutton_1_chieu.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        radiobutton_1_chieu.setForeground(new java.awt.Color(255, 255, 255));
        radiobutton_1_chieu.setText("Một chiều");

        lbl_diem_den.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_diem_den.setForeground(new java.awt.Color(255, 255, 255));
        lbl_diem_den.setText("Điểm đến:");

        jComboBox1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội (HAN), Việt Nam", "Tp. Hồ Chí Minh (SGN), Việt Nam", "Đà Nẵng (DAD), Việt Nam", "Phú Quốc (PQC), Việt Nam", "Nha Trang (CXR), Việt Nam", "Buôn Ma Thuột (BMV), Việt Nam", "Cà Mau (CAH), Việt Nam", "Cần Thơ (VCA), Việt Nam", "Chu Lai (VCL), Việt Nam", "Côn Đảo (VCS), Việt Nam", "Đà Lạt (DLI), Việt Nam", "Điện Biên (DIN), Việt Nam", "Đồng Hới (VDH), Việt Nam", "Hải Phòng (HPH), Việt Nam", "Huế (HUI), Việt Nam", "Pleiku (PXU), Việt Nam", "Quy Nhơn (UIH), Việt Nam", "Rạch Giá (VKG), Việt Nam", "Thanh Hóa (THD), Việt Nam", "Tuy Hòa (TBB), Việt Nam", "Vân Đồn (VDO), Việt Nam", "Vinh (VII), Việt Nam" }));

        lbl_diem_khoi_hanh.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_diem_khoi_hanh.setForeground(new java.awt.Color(255, 255, 255));
        lbl_diem_khoi_hanh.setText("Điểm khởi hành:");

        jComboBox2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội (HAN), Việt Nam", "Tp. Hồ Chí Minh (SGN), Việt Nam", "Đà Nẵng (DAD), Việt Nam", "Phú Quốc (PQC), Việt Nam", "Nha Trang (CXR), Việt Nam", "Buôn Ma Thuột (BMV), Việt Nam", "Cà Mau (CAH), Việt Nam", "Cần Thơ (VCA), Việt Nam", "Chu Lai (VCL), Việt Nam", "Côn Đảo (VCS), Việt Nam", "Đà Lạt (DLI), Việt Nam", "Điện Biên (DIN), Việt Nam", "Đồng Hới (VDH), Việt Nam", "Hải Phòng (HPH), Việt Nam", "Huế (HUI), Việt Nam", "Pleiku (PXU), Việt Nam", "Quy Nhơn (UIH), Việt Nam", "Rạch Giá (VKG), Việt Nam", "Thanh Hóa (THD), Việt Nam", "Tuy Hòa (TBB), Việt Nam", "Vân Đồn (VDO), Việt Nam", "Vinh (VII), Việt Nam", " " }));

        lbl_so_luong_hanh_khach.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_so_luong_hanh_khach.setForeground(new java.awt.Color(255, 255, 255));
        lbl_so_luong_hanh_khach.setText("Số lượng hành khách:");

        jComboBox3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        lbl_ngay_bay.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_ngay_bay.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ngay_bay.setText("Ngày bay:");

        jDateChooser1.setDateFormatString("dd/MM/yyyy\n");
        jDateChooser1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        btn_tim_chuyen_bay.setBackground(new java.awt.Color(255, 255, 0));
        btn_tim_chuyen_bay.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btn_tim_chuyen_bay.setText("Tìm chuyến bay");

        javax.swing.GroupLayout pn_tim_kiem_chuyen_bayLayout = new javax.swing.GroupLayout(pn_tim_kiem_chuyen_bay);
        pn_tim_kiem_chuyen_bay.setLayout(pn_tim_kiem_chuyen_bayLayout);
        pn_tim_kiem_chuyen_bayLayout.setHorizontalGroup(
            pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tim_kiem_chuyen_bayLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_tim_kiem_chuyen_bayLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_tim_chuyen_bay)
                        .addGap(528, 528, 528))
                    .addGroup(pn_tim_kiem_chuyen_bayLayout.createSequentialGroup()
                        .addGroup(pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiobutton_1_chieu)
                            .addGroup(pn_tim_kiem_chuyen_bayLayout.createSequentialGroup()
                                .addGroup(pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_diem_khoi_hanh, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_diem_den, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_so_luong_hanh_khach)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ngay_bay)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        pn_tim_kiem_chuyen_bayLayout.setVerticalGroup(
            pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tim_kiem_chuyen_bayLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(radiobutton_1_chieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_tim_kiem_chuyen_bayLayout.createSequentialGroup()
                        .addComponent(lbl_ngay_bay)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(pn_tim_kiem_chuyen_bayLayout.createSequentialGroup()
                        .addGroup(pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_diem_den, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_so_luong_hanh_khach)
                            .addComponent(lbl_diem_khoi_hanh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_tim_kiem_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_tim_chuyen_bay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã vé", "Điểm khởi hành", "Điểm đến", "Ngày bay", "Thời gian bay", "Số lượng hành khách"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(jTable2);

        btn_tiep_tuc.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_tiep_tuc.setText("Tiếp tục");

        javax.swing.GroupLayout pnContainer1Layout = new javax.swing.GroupLayout(pnContainer1);
        pnContainer1.setLayout(pnContainer1Layout);
        pnContainer1Layout.setHorizontalGroup(
            pnContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_tim_kiem_chuyen_bay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnContainer1Layout.createSequentialGroup()
                .addGap(544, 544, 544)
                .addComponent(btn_tiep_tuc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        pnContainer1Layout.setVerticalGroup(
            pnContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContainer1Layout.createSequentialGroup()
                .addComponent(pn_tim_kiem_chuyen_bay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_tiep_tuc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardDatVeLayout = new javax.swing.GroupLayout(cardDatVe);
        cardDatVe.setLayout(cardDatVeLayout);
        cardDatVeLayout.setHorizontalGroup(
            cardDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardDatVeLayout.setVerticalGroup(
            cardDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jplMain.add(cardDatVe, "card4");

        cardVeCuaToi.setPreferredSize(new java.awt.Dimension(1200, 750));

        pnContainer2.setBackground(new java.awt.Color(255, 255, 255));
        pnContainer2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnContainer2.setPreferredSize(new java.awt.Dimension(1200, 750));

        pnTitle2.setBackground(new java.awt.Color(204, 0, 0));
        pnTitle2.setPreferredSize(new java.awt.Dimension(1200, 100));

        lbl_ve_cua_toi.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lbl_ve_cua_toi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ve_cua_toi.setText("VÉ CỦA TÔI");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/ticket.png"))); // NOI18N

        javax.swing.GroupLayout pnTitle2Layout = new javax.swing.GroupLayout(pnTitle2);
        pnTitle2.setLayout(pnTitle2Layout);
        pnTitle2Layout.setHorizontalGroup(
            pnTitle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitle2Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbl_ve_cua_toi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTitle2Layout.setVerticalGroup(
            pnTitle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitle2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(pnTitle2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_ve_cua_toi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnTicket.setBackground(new java.awt.Color(255, 255, 255));
        pnTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnTicket.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 1, 10, 300));

        pnTitle.setBackground(new java.awt.Color(204, 0, 0));

        jLabel27.setFont(new java.awt.Font("Segoe UI Historic", 0, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("CLC04 AirLines");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/logoticket.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Boarding pass");

        jLabel30.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("ECONOMY");

        jLabel31.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Boarding pass");

        jLabel32.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("ECONOMY");

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(231, 231, 231)
                .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30))
                .addGap(19, 19, 19))
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32)))
                    .addComponent(jLabel29)
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel27)))
                .addContainerGap())
        );

        pnTicket.add(pnTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        pnBorder.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout pnBorderLayout = new javax.swing.GroupLayout(pnBorder);
        pnBorder.setLayout(pnBorderLayout);
        pnBorderLayout.setHorizontalGroup(
            pnBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnBorderLayout.setVerticalGroup(
            pnBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnTicket.add(pnBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 283, 1200, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Passenger name:");
        pnTicket.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, -1, -1));

        lbl_passenger_name.setText("jLabel6");
        pnTicket.add(lbl_passenger_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 153, 118, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setText("From:");
        pnTicket.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 55, 20));

        lbl_from.setText("jLabel6");
        pnTicket.add(lbl_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 200, 118, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel9.setText("To:");
        pnTicket.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 49, -1));

        lbl_to.setText("jLabel6");
        pnTicket.add(lbl_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 247, 118, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel14.setText("Date:");
        pnTicket.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, 43, -1));

        lbl_date.setText("jLabel6");
        pnTicket.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 153, 135, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel16.setText("Flight:");
        pnTicket.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel18.setText("Gate:");
        pnTicket.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, -1, -1));

        lbl_flight.setText("jLabel6");
        pnTicket.add(lbl_flight, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 200, 135, -1));

        lbl_board_till.setText("jLabel6");
        pnTicket.add(lbl_board_till, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 247, 131, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel21.setText("Seat:");
        pnTicket.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 170, 43, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel22.setText("Time:");
        pnTicket.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 130, 43, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel23.setText("Board till:");
        pnTicket.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 222, -1, -1));

        lbl_to1.setText("jLabel6");
        pnTicket.add(lbl_to1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 131, 20));

        lbl_seat.setText("jLabel6");
        pnTicket.add(lbl_seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 200, 131, -1));

        lbl_gate.setText("jLabel6");
        pnTicket.add(lbl_gate, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 247, 135, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel33.setText("Passenger name:");
        pnTicket.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 128, -1, -1));

        lbl_time.setText("jLabel6");
        pnTicket.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 153, 131, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel35.setText("From:");
        pnTicket.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 175, 55, -1));

        lbl_gate1.setText("jLabel6");
        pnTicket.add(lbl_gate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, 50, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel37.setText("To:");
        pnTicket.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 222, 49, -1));

        lbl_from1.setText("jLabel6");
        pnTicket.add(lbl_from1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 131, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel39.setText("Date:");
        pnTicket.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 128, 43, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel40.setText("Time:");
        pnTicket.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 128, 43, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel41.setText("Flight:");
        pnTicket.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 175, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel42.setText("Seat:");
        pnTicket.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 175, 43, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel43.setText("Gate:");
        pnTicket.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 222, -1, -1));

        lbl_passenger_name1.setText("jLabel6");
        pnTicket.add(lbl_passenger_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 120, -1));

        jLabel45.setText("jLabel6");
        pnTicket.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 131, -1));

        lbl_date1.setText("jLabel6");
        pnTicket.add(lbl_date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 150, 50, -1));

        lbl_time1.setText("jLabel6");
        pnTicket.add(lbl_time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 150, 50, -1));

        lbl_flight1.setText("jLabel6");
        pnTicket.add(lbl_flight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, 50, -1));

        lbl_seat1.setText("jLabel6");
        pnTicket.add(lbl_seat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 190, 50, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnContainer2Layout = new javax.swing.GroupLayout(pnContainer2);
        pnContainer2.setLayout(pnContainer2Layout);
        pnContainer2Layout.setHorizontalGroup(
            pnContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnContainer2Layout.setVerticalGroup(
            pnContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContainer2Layout.createSequentialGroup()
                .addComponent(pnTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout cardVeCuaToiLayout = new javax.swing.GroupLayout(cardVeCuaToi);
        cardVeCuaToi.setLayout(cardVeCuaToiLayout);
        cardVeCuaToiLayout.setHorizontalGroup(
            cardVeCuaToiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE)
        );
        cardVeCuaToiLayout.setVerticalGroup(
            cardVeCuaToiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );

        jplMain.add(cardVeCuaToi, "card5");

        cardHoSo.setPreferredSize(new java.awt.Dimension(1200, 750));

        pnContainer3.setBackground(new java.awt.Color(255, 255, 255));
        pnContainer3.setPreferredSize(new java.awt.Dimension(1200, 750));

        pnTitle1.setBackground(new java.awt.Color(204, 0, 0));

        lbl_ho_so.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lbl_ho_so.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ho_so.setText("HỒ SƠ");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/hoso.png"))); // NOI18N

        javax.swing.GroupLayout pnTitle1Layout = new javax.swing.GroupLayout(pnTitle1);
        pnTitle1.setLayout(pnTitle1Layout);
        pnTitle1Layout.setHorizontalGroup(
            pnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitle1Layout.createSequentialGroup()
                .addGap(444, 444, 444)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ho_so)
                .addContainerGap(538, Short.MAX_VALUE))
        );
        pnTitle1Layout.setVerticalGroup(
            pnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitle1Layout.createSequentialGroup()
                .addGroup(pnTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTitle1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbl_ho_so))
                    .addGroup(pnTitle1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lbl_so_dien_thoai.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_so_dien_thoai.setText("SỐ ĐIỆN THOẠI:");

        lbl_email.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_email.setText("EMAIL:");

        lbl_cmnd.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_cmnd.setText("CMND:");

        lbl_ho_va_ten.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_ho_va_ten.setText("HỌ VÀ TÊN:");

        lbl_gioi_tinh.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_gioi_tinh.setText("GIỚI TÍNH:");

        lbl_mat_khau.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_mat_khau.setText("MẬT KHẨU:");

        btn_doi_mat_khau.setBackground(new java.awt.Color(204, 0, 51));
        btn_doi_mat_khau.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_doi_mat_khau.setForeground(new java.awt.Color(255, 255, 255));
        btn_doi_mat_khau.setText("ĐỔI THÔNG TIN");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/ava.png"))); // NOI18N

        javax.swing.GroupLayout pnContainer3Layout = new javax.swing.GroupLayout(pnContainer3);
        pnContainer3.setLayout(pnContainer3Layout);
        pnContainer3Layout.setHorizontalGroup(
            pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnContainer3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ho_va_ten)
                    .addComponent(lbl_so_dien_thoai)
                    .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_gioi_tinh)
                    .addComponent(lbl_mat_khau)
                    .addComponent(lbl_cmnd))
                .addGap(60, 60, 60)
                .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnContainer3Layout.createSequentialGroup()
                        .addComponent(cmnd_field, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnContainer3Layout.createSequentialGroup()
                        .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnContainer3Layout.createSequentialGroup()
                                .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gioi_tinh_field)
                                    .addComponent(ten_dang_nhap_field)
                                    .addComponent(email_field, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addComponent(btn_doi_mat_khau)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnContainer3Layout.createSequentialGroup()
                                .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(so_dien_thoai_field, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ho_va_ten_field))
                                .addGap(242, 242, 242)))
                        .addComponent(jLabel17)))
                .addGap(28, 28, 28))
        );
        pnContainer3Layout.setVerticalGroup(
            pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContainer3Layout.createSequentialGroup()
                .addComponent(pnTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_cmnd)
                    .addComponent(cmnd_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnContainer3Layout.createSequentialGroup()
                        .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ho_va_ten_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ho_va_ten))
                        .addGap(35, 35, 35)
                        .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_so_dien_thoai)
                            .addComponent(so_dien_thoai_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_email)
                            .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gioi_tinh_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_gioi_tinh))
                        .addGap(35, 35, 35)
                        .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_mat_khau)
                            .addGroup(pnContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ten_dang_nhap_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_doi_mat_khau, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel17))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardHoSoLayout = new javax.swing.GroupLayout(cardHoSo);
        cardHoSo.setLayout(cardHoSoLayout);
        cardHoSoLayout.setHorizontalGroup(
            cardHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardHoSoLayout.setVerticalGroup(
            cardHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jplMain.add(cardHoSo, "card5");

        pnContainer.add(jplMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMenuMouseClicked
        closeMenu();
    }//GEN-LAST:event_lblCloseMenuMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jplSlideMenu.setSize(0, y);
        x = 0;
    }//GEN-LAST:event_formWindowOpened

    private void lblTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseClicked
        cardTrangChu.setVisible(true);
        cardDatVe.setVisible(false);
        cardVeCuaToi.setVisible(false);
        cardHoSo.setVisible(false);
    }//GEN-LAST:event_lblTrangChuMouseClicked

    private void lblDatVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDatVeMouseClicked
        cardTrangChu.setVisible(false);
        cardDatVe.setVisible(true);
        cardVeCuaToi.setVisible(false);
        cardHoSo.setVisible(false);
    }//GEN-LAST:event_lblDatVeMouseClicked

    private void lblVeCuaToiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVeCuaToiMouseClicked
        cardTrangChu.setVisible(false);
        cardVeCuaToi.setVisible(true);
        cardDatVe.setVisible(false);
        cardHoSo.setVisible(false);
    }//GEN-LAST:event_lblVeCuaToiMouseClicked

    private void lblHoSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoSoMouseClicked
        cardTrangChu.setVisible(false);
        cardHoSo.setVisible(true);
        cardVeCuaToi.setVisible(false);
        cardDatVe.setVisible(false);
    }//GEN-LAST:event_lblHoSoMouseClicked

    private void lbl_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuMouseClicked
        openMenu();
    }//GEN-LAST:event_lbl_menuMouseClicked

    private void label_dang_xuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_dang_xuatMouseClicked
        dispose();
        Login l = new Login();
        l.setVisible(true);
        l.pack();
        l.setLocationRelativeTo(null);
    }//GEN-LAST:event_label_dang_xuatMouseClicked

    private void mat_khau_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat_khau_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat_khau_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_doi_mat_khau;
    private javax.swing.JButton btn_tiep_tuc;
    private javax.swing.JButton btn_tim_chuyen_bay;
    private javax.swing.JPanel cardDatVe;
    private javax.swing.JPanel cardHoSo;
    private javax.swing.JPanel cardTrangChu;
    private javax.swing.JPanel cardVeCuaToi;
    private javax.swing.JTextField cmnd_field;
    private javax.swing.JPanel container_avatar_close;
    private javax.swing.JTextField email_field;
    private javax.swing.JTextField gioi_tinh_field;
    private javax.swing.JTextField ho_va_ten_field;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel jplMain;
    private javax.swing.JPanel jplSlideMenu;
    private javax.swing.JLabel label_dang_xuat;
    private javax.swing.JLabel lblCloseMenu;
    private javax.swing.JLabel lblDatVe;
    private javax.swing.JLabel lblHoSo;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JLabel lblVeCuaToi;
    private javax.swing.JLabel lbl_board_till;
    private javax.swing.JLabel lbl_cmnd;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_date1;
    private javax.swing.JLabel lbl_diem_den;
    private javax.swing.JLabel lbl_diem_khoi_hanh;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_flight;
    private javax.swing.JLabel lbl_flight1;
    private javax.swing.JLabel lbl_from;
    private javax.swing.JLabel lbl_from1;
    private javax.swing.JLabel lbl_gate;
    private javax.swing.JLabel lbl_gate1;
    private javax.swing.JLabel lbl_gioi_tinh;
    private javax.swing.JLabel lbl_ho_so;
    private javax.swing.JLabel lbl_ho_va_ten;
    private javax.swing.JLabel lbl_mat_khau;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JLabel lbl_ngay_bay;
    private javax.swing.JLabel lbl_passenger_name;
    private javax.swing.JLabel lbl_passenger_name1;
    private javax.swing.JLabel lbl_seat;
    private javax.swing.JLabel lbl_seat1;
    private javax.swing.JLabel lbl_so_dien_thoai;
    private javax.swing.JLabel lbl_so_luong_hanh_khach;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_time1;
    private javax.swing.JLabel lbl_to;
    private javax.swing.JLabel lbl_to1;
    private javax.swing.JLabel lbl_ve_cua_toi;
    private javax.swing.JTextField mat_khau_field;
    private javax.swing.JPanel pnBorder;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnContainer1;
    private javax.swing.JPanel pnContainer2;
    private javax.swing.JPanel pnContainer3;
    private javax.swing.JPanel pnTicket;
    private javax.swing.JPanel pnTitle;
    private javax.swing.JPanel pnTitle1;
    private javax.swing.JPanel pnTitle2;
    private javax.swing.JPanel pn_tim_kiem_chuyen_bay;
    private javax.swing.JRadioButton radiobutton_1_chieu;
    private javax.swing.JTextField so_dien_thoai_field;
    private javax.swing.JTextField ten_dang_nhap_field;
    private javax.swing.JPanel thanh_menu;
    // End of variables declaration//GEN-END:variables
}
