/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.main;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    int x = 210;    //chieu rong
    int y = 590;    //chieu cao

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        cardTrangChu.setVisible(true);
        cardDatVe.setVisible(false);
        jplSlideMenu.setSize(210,600);
    }

    public void openMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 0) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 0; i <= 210; i++) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(1);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 210;
        }
    }

    public void closeMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 210) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 210; i >= 0; i--) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(2);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnContainer = new javax.swing.JPanel();
        thanh_menu = new javax.swing.JPanel();
        lblOpenMenu = new javax.swing.JLabel();
        jplSlideMenu = new javax.swing.JPanel();
        container_avatar_close = new javax.swing.JPanel();
        lblCloseMenu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTrangChu = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_dang_xuat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jplMain = new javax.swing.JPanel();
        cardTrangChu = new javax.swing.JPanel();
        khung_tim_chuyen_bay = new javax.swing.JPanel();
        mot_chieu = new javax.swing.JRadioButton();
        khu_hoi = new javax.swing.JRadioButton();
        tien_te = new javax.swing.JLabel();
        diem_den = new javax.swing.JComboBox<>();
        nut_tim_chuyen_bay = new javax.swing.JButton();
        diem_khoi_hanh = new javax.swing.JComboBox<>();
        label_ngay_di = new javax.swing.JLabel();
        label_khoi_hanh = new javax.swing.JLabel();
        label_diem_den = new javax.swing.JLabel();
        chon_ngay_di = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        cardDatVe = new javax.swing.JPanel();

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("TRANG CHỦ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        thanh_menu.setBackground(new java.awt.Color(255, 255, 255));

        lblOpenMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        lblOpenMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout thanh_menuLayout = new javax.swing.GroupLayout(thanh_menu);
        thanh_menu.setLayout(thanh_menuLayout);
        thanh_menuLayout.setHorizontalGroup(
            thanh_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thanh_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOpenMenu)
                .addContainerGap(903, Short.MAX_VALUE))
        );
        thanh_menuLayout.setVerticalGroup(
            thanh_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thanh_menuLayout.createSequentialGroup()
                .addComponent(lblOpenMenu)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pnContainer.add(thanh_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 40));

        jplSlideMenu.setBackground(new java.awt.Color(255, 255, 255));
        jplSlideMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jplSlideMenu.setPreferredSize(new java.awt.Dimension(210, 590));
        jplSlideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container_avatar_close.setBackground(new java.awt.Color(255, 255, 255));
        container_avatar_close.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCloseMenu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCloseMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseMenu.setText("X");
        lblCloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMenuMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/avatar.png"))); // NOI18N

        javax.swing.GroupLayout container_avatar_closeLayout = new javax.swing.GroupLayout(container_avatar_close);
        container_avatar_close.setLayout(container_avatar_closeLayout);
        container_avatar_closeLayout.setHorizontalGroup(
            container_avatar_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_avatar_closeLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        container_avatar_closeLayout.setVerticalGroup(
            container_avatar_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_avatar_closeLayout.createSequentialGroup()
                .addGroup(container_avatar_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCloseMenu)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jplSlideMenu.add(container_avatar_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Thống Kê");
        jplSlideMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 210, 30));

        lblTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        lblTrangChu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrangChu.setText("Trang Chủ");
        lblTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseClicked(evt);
            }
        });
        jplSlideMenu.add(lblTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 30));

        lblTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaiKhoan.setText("Đặt vé");
        lblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMouseClicked(evt);
            }
        });
        jplSlideMenu.add(lblTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hóa Đơn");
        jplSlideMenu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 30));
        jplSlideMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 210, 10));

        label_dang_xuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_dang_xuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_dang_xuat.setText("Đăng Xuất");
        jplSlideMenu.add(label_dang_xuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 210, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Giới Thiệu");
        jplSlideMenu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 210, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Trợ Giúp");
        jplSlideMenu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 210, 30));

        pnContainer.add(jplSlideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 0, 590));

        jplMain.setBackground(new java.awt.Color(255, 255, 255));
        jplMain.setLayout(new java.awt.CardLayout());

        cardTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        cardTrangChu.setLayout(null);

        khung_tim_chuyen_bay.setBackground(new java.awt.Color(204, 0, 0));
        khung_tim_chuyen_bay.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        mot_chieu.setBackground(new java.awt.Color(204, 0, 0));
        buttonGroup1.add(mot_chieu);
        mot_chieu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        mot_chieu.setForeground(new java.awt.Color(255, 255, 255));
        mot_chieu.setText("Một chiều");
        mot_chieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mot_chieuActionPerformed(evt);
            }
        });

        khu_hoi.setBackground(new java.awt.Color(204, 0, 0));
        buttonGroup1.add(khu_hoi);
        khu_hoi.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        khu_hoi.setForeground(new java.awt.Color(255, 255, 255));
        khu_hoi.setText("Khứ hồi");

        tien_te.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        tien_te.setForeground(new java.awt.Color(255, 255, 255));
        tien_te.setText("VND");

        diem_den.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        diem_den.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội (HAN), Việt Nam", "Tp. Hồ Chí Minh (SGN), Việt Nam", "Đà Nẵng (DAD), Việt Nam", "Phú Quốc (PQC), Việt Nam", "Nha Trang (CXR), Việt Nam", "Buôn Ma Thuột (BMV), Việt Nam", "Cà Mau (CAH), Việt Nam", "Cần Thơ (VCA), Việt Nam", "Chu Lai (VCL), Việt Nam", "Côn Đảo (VCS), Việt Nam", "Đà Lạt (DLI), Việt Nam", "Điện Biên (DIN), Việt Nam", "Đồng Hới (VDH), Việt Nam", "Hải Phòng (HPH), Việt Nam", "Huế (HUI), Việt Nam", "Pleiku (PXU), Việt Nam", "Quy Nhơn (UIH), Việt Nam", "Rạch Giá (VKG), Việt Nam", "Thanh Hóa (THD), Việt Nam", "Tuy Hòa (TBB), Việt Nam", "Vân Đồn (VDO), Việt Nam", "Vinh (VII), Việt Nam", " " }));

        nut_tim_chuyen_bay.setBackground(new java.awt.Color(255, 255, 0));
        nut_tim_chuyen_bay.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        nut_tim_chuyen_bay.setText("Tìm chuyến bay");

        diem_khoi_hanh.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        diem_khoi_hanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội (HAN), Việt Nam", "Tp. Hồ Chí Minh (SGN), Việt Nam", "Đà Nẵng (DAD), Việt Nam", "Phú Quốc (PQC), Việt Nam", "Nha Trang (CXR), Việt Nam", "Buôn Ma Thuột (BMV), Việt Nam", "Cà Mau (CAH), Việt Nam", "Cần Thơ (VCA), Việt Nam", "Chu Lai (VCL), Việt Nam", "Côn Đảo (VCS), Việt Nam", "Đà Lạt (DLI), Việt Nam", "Điện Biên (DIN), Việt Nam", "Đồng Hới (VDH), Việt Nam", "Hải Phòng (HPH), Việt Nam", "Huế (HUI), Việt Nam", "Pleiku (PXU), Việt Nam", "Quy Nhơn (UIH), Việt Nam", "Rạch Giá (VKG), Việt Nam", "Thanh Hóa (THD), Việt Nam", "Tuy Hòa (TBB), Việt Nam", "Vân Đồn (VDO), Việt Nam", "Vinh (VII), Việt Nam", " " }));
        diem_khoi_hanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diem_khoi_hanhActionPerformed(evt);
            }
        });

        label_ngay_di.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        label_ngay_di.setForeground(new java.awt.Color(255, 255, 255));
        label_ngay_di.setText("Ngày đi:");

        label_khoi_hanh.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        label_khoi_hanh.setForeground(new java.awt.Color(255, 255, 255));
        label_khoi_hanh.setText("Điểm khởi hành:");

        label_diem_den.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        label_diem_den.setForeground(new java.awt.Color(255, 255, 255));
        label_diem_den.setText("Điểm đến:");

        chon_ngay_di.setDateFormatString("dd/MM/yyyy");
        chon_ngay_di.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout khung_tim_chuyen_bayLayout = new javax.swing.GroupLayout(khung_tim_chuyen_bay);
        khung_tim_chuyen_bay.setLayout(khung_tim_chuyen_bayLayout);
        khung_tim_chuyen_bayLayout.setHorizontalGroup(
            khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chon_ngay_di, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diem_khoi_hanh, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diem_den, 0, 306, Short.MAX_VALUE)
                    .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                        .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_diem_den)
                            .addComponent(label_ngay_di)
                            .addComponent(label_khoi_hanh))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                        .addComponent(mot_chieu)
                        .addGap(33, 33, 33)
                        .addComponent(khu_hoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tien_te)))
                .addContainerGap())
            .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(nut_tim_chuyen_bay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        khung_tim_chuyen_bayLayout.setVerticalGroup(
            khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mot_chieu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khu_hoi)
                    .addComponent(tien_te))
                .addGap(18, 18, 18)
                .addComponent(label_khoi_hanh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diem_khoi_hanh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_diem_den)
                .addGap(11, 11, 11)
                .addComponent(diem_den, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_ngay_di)
                .addGap(18, 18, 18)
                .addComponent(chon_ngay_di, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nut_tim_chuyen_bay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        cardTrangChu.add(khung_tim_chuyen_bay);
        khung_tim_chuyen_bay.setBounds(590, 110, 320, 390);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        cardTrangChu.add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 590);

        jplMain.add(cardTrangChu, "card2");

        cardDatVe.setBackground(new java.awt.Color(255, 255, 255));
        cardDatVe.setLayout(null);
        jplMain.add(cardDatVe, "card3");

        pnContainer.add(jplMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMenuMouseClicked
        closeMenu();
    }//GEN-LAST:event_lblCloseMenuMouseClicked

    private void lblOpenMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenMenuMouseClicked
        openMenu();
    }//GEN-LAST:event_lblOpenMenuMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jplSlideMenu.setSize(0, y);
        x = 0;
    }//GEN-LAST:event_formWindowOpened

    private void lblTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseClicked
        cardTrangChu.setVisible(true);
        cardDatVe.setVisible(false);
    }//GEN-LAST:event_lblTrangChuMouseClicked

    private void lblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseClicked
        cardTrangChu.setVisible(false);
        cardDatVe.setVisible(true);
    }//GEN-LAST:event_lblTaiKhoanMouseClicked

    private void mot_chieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mot_chieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mot_chieuActionPerformed

    private void diem_khoi_hanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diem_khoi_hanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diem_khoi_hanhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cardDatVe;
    private javax.swing.JPanel cardTrangChu;
    private com.toedter.calendar.JDateChooser chon_ngay_di;
    private javax.swing.JPanel container_avatar_close;
    private javax.swing.JComboBox<String> diem_den;
    private javax.swing.JComboBox<String> diem_khoi_hanh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jplMain;
    private javax.swing.JPanel jplSlideMenu;
    private javax.swing.JRadioButton khu_hoi;
    private javax.swing.JPanel khung_tim_chuyen_bay;
    private javax.swing.JLabel label_dang_xuat;
    private javax.swing.JLabel label_diem_den;
    private javax.swing.JLabel label_khoi_hanh;
    private javax.swing.JLabel label_ngay_di;
    private javax.swing.JLabel lblCloseMenu;
    private javax.swing.JLabel lblOpenMenu;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JRadioButton mot_chieu;
    private javax.swing.JButton nut_tim_chuyen_bay;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel thanh_menu;
    private javax.swing.JLabel tien_te;
    // End of variables declaration//GEN-END:variables
}
