/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.main;

import java.awt.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.*;

import DataHandle.Data.Users;
import Models.Flightxtended;
import Models.Ticket;
import Models.User;
import System.AirlineSystem;
import UI.main.CustomPlugin.*;

/**
 * @author User
 */
public class Menu extends javax.swing.JFrame {
    private AirlineSystem manager = new AirlineSystem();
    private int userID;

    int x = 300;    //chieu rong
    int y = 750;    //chieu cao

    /**
     * Creates new form Menu
     */
    public Menu(int userID) {
        initComponents();
        cardTrangChu.setVisible(true);
        jplSlideMenu.setSize(300, 750);
        this.userID = userID;
    }


    public Menu() {
        initComponents();
        cardTrangChu.setVisible(true);
        jplSlideMenu.setSize(300, 750);
    }

    public void openMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 0) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 0; i <= 300; i++) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(2);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 300;
        }
    }

    public void closeMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 300) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 300; i >= 0; i--) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(2);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContainer = new javax.swing.JPanel();
        thanh_menu = new javax.swing.JPanel();
        lbl_menu = new javax.swing.JLabel();
        jplSlideMenu = new javax.swing.JPanel();
        container_avatar_close = new javax.swing.JPanel();
        lblCloseMenu = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblHoSo = new javax.swing.JLabel();
        lblTrangChu = new javax.swing.JLabel();
        lblDatVe = new javax.swing.JLabel();
        lblVeCuaToi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_dang_xuat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jplMain = new javax.swing.JPanel();
        cardTrangChu = new javax.swing.JPanel();
        HomePage = new BackGroundChangedByTime();
        cardDatVe = new javax.swing.JPanel();
        pnContainer1 = new javax.swing.JPanel();
        khung_tim_chuyen_bay = new javax.swing.JPanel();
        mot_chieu = new javax.swing.JRadioButton();
        diem_den = new javax.swing.JComboBox<>();
        nut_tim_chuyen_bay = new javax.swing.JButton();
        diem_khoi_hanh = new javax.swing.JComboBox<>();
        label_ngay_di = new javax.swing.JLabel();
        label_khoi_hanh = new javax.swing.JLabel();
        label_diem_den = new javax.swing.JLabel();
        ngay_di = new com.toedter.calendar.JDateChooser();
        so_khach_combobox = new javax.swing.JComboBox<>();
        label_ngay_di1 = new javax.swing.JLabel();
        FlightScroll = new javax.swing.JScrollPane();
        FlightFoundedPane = new javax.swing.JPanel();
        cardHoSo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JTextField();
        ChangeMailButton = new javax.swing.JButton();
        ChangePasswordButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        gmailField = new javax.swing.JLabel();
        UserNameField = new javax.swing.JLabel();
        profImagePane = new ImagePanel("/UI/Icon/hoso.png");
        jPanel7 = new javax.swing.JPanel();
        cardVeCuaToi = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MyTicketScroll = new javax.swing.JScrollPane();
        MyTicketPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnContainer.setPreferredSize(new java.awt.Dimension(1200, 800));
        pnContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        thanh_menu.setBackground(new java.awt.Color(255, 255, 255));

        lbl_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/menu.png"))); // NOI18N
        lbl_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout thanh_menuLayout = new javax.swing.GroupLayout(thanh_menu);
        thanh_menu.setLayout(thanh_menuLayout);
        thanh_menuLayout.setHorizontalGroup(
            thanh_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thanh_menuLayout.createSequentialGroup()
                .addComponent(lbl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1150, Short.MAX_VALUE))
        );
        thanh_menuLayout.setVerticalGroup(
            thanh_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_menu)
        );

        pnContainer.add(thanh_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jplSlideMenu.setBackground(new java.awt.Color(255, 255, 255));
        jplSlideMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jplSlideMenu.setPreferredSize(new java.awt.Dimension(300, 750));

        container_avatar_close.setBackground(new java.awt.Color(255, 255, 255));
        container_avatar_close.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCloseMenu.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lblCloseMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseMenu.setText("X");
        lblCloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMenuMouseClicked(evt);
            }
        });

        jPanel5 = new ImagePanel("/UI/Icon/avatar.png");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout container_avatar_closeLayout = new javax.swing.GroupLayout(container_avatar_close);
        container_avatar_close.setLayout(container_avatar_closeLayout);
        container_avatar_closeLayout.setHorizontalGroup(
            container_avatar_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_avatar_closeLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        container_avatar_closeLayout.setVerticalGroup(
            container_avatar_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_avatar_closeLayout.createSequentialGroup()
                .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
            .addGroup(container_avatar_closeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblHoSo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHoSo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoSo.setText("Hồ sơ");
        lblHoSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    lblHoSoMouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        lblTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        lblTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrangChu.setText("Trang Chủ");
        lblTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseClicked(evt);
            }
        });

        lblDatVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDatVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatVe.setText("Đặt vé");
        lblDatVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDatVeMouseClicked(evt);
            }
        });

        lblVeCuaToi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVeCuaToi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVeCuaToi.setText("Vé của tôi");
        lblVeCuaToi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVeCuaToiMouseClicked(evt);
            }
        });

        label_dang_xuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_dang_xuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_dang_xuat.setText("Đăng Xuất");
        label_dang_xuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_dang_xuatMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Giới Thiệu");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Trợ Giúp");

        javax.swing.GroupLayout jplSlideMenuLayout = new javax.swing.GroupLayout(jplSlideMenu);
        jplSlideMenu.setLayout(jplSlideMenuLayout);
        jplSlideMenuLayout.setHorizontalGroup(
            jplSlideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container_avatar_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblDatVe, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblVeCuaToi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(label_dang_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jplSlideMenuLayout.setVerticalGroup(
            jplSlideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplSlideMenuLayout.createSequentialGroup()
                .addComponent(container_avatar_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblDatVe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblVeCuaToi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_dang_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pnContainer.add(jplSlideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 0, -1));

        jplMain.setBackground(new java.awt.Color(255, 255, 255));
        jplMain.setPreferredSize(new java.awt.Dimension(1200, 750));
        jplMain.setLayout(new java.awt.CardLayout());

        cardTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        cardTrangChu.setPreferredSize(new java.awt.Dimension(1200, 750));

        javax.swing.GroupLayout HomePageLayout = new javax.swing.GroupLayout(HomePage);
        HomePage.setLayout(HomePageLayout);
        HomePageLayout.setHorizontalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        HomePageLayout.setVerticalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardTrangChuLayout = new javax.swing.GroupLayout(cardTrangChu);
        cardTrangChu.setLayout(cardTrangChuLayout);
        cardTrangChuLayout.setHorizontalGroup(
            cardTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        cardTrangChuLayout.setVerticalGroup(
            cardTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jplMain.add(cardTrangChu, "card2");

        cardDatVe.setPreferredSize(new java.awt.Dimension(1200, 750));

        pnContainer1.setBackground(new java.awt.Color(255, 255, 255));
        pnContainer1.setMinimumSize(new java.awt.Dimension(1200, 750));
        pnContainer1.setPreferredSize(new java.awt.Dimension(1200, 750));
        pnContainer1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        khung_tim_chuyen_bay.setBackground(new java.awt.Color(204, 0, 0));
        khung_tim_chuyen_bay.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        khung_tim_chuyen_bay.setPreferredSize(new java.awt.Dimension(1200, 200));

        mot_chieu.setBackground(new java.awt.Color(204, 0, 0));
        mot_chieu.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        mot_chieu.setForeground(new java.awt.Color(255, 255, 255));
        mot_chieu.setText("Một chiều");
        mot_chieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mot_chieuActionPerformed(evt);
            }
        });

        diem_den.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        diem_den.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quang Nam", "Thanh Hoa", "Quang Binh", "Dien Bien", "Phu Yen", "Gia Lai", "Dak Lak", "Kien Giang", "Ca Mau", "Ba Ria – Vung Tau", "Ha Noi", "Thanh pho Ho Chi Minh", "Kien Giang", "Da Nang", "Khanh Hoa", "Thua Thien Hue", "Quang Ninh", "Can Tho", "Nghe An", "Binh Dinh", "Hai Phong", "Lam Dong" }));
        diem_den.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diem_denActionPerformed(evt);
            }
        });

        nut_tim_chuyen_bay.setBackground(new java.awt.Color(255, 255, 0));
        nut_tim_chuyen_bay.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        nut_tim_chuyen_bay.setText("Tìm chuyến bay");
        nut_tim_chuyen_bay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut_tim_chuyen_bayActionPerformed(evt);
            }
        });

        diem_khoi_hanh.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        diem_khoi_hanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quang Nam", "Thanh Hoa", "Quang Binh", "Dien Bien", "Phu Yen", "Gia Lai", "Dak Lak", "Kien Giang", "Ca Mau", "Ba Ria – Vung Tau", "Ha Noi", "Thanh pho Ho Chi Minh", "Kien Giang", "Da Nang", "Khanh Hoa", "Thua Thien Hue", "Quang Ninh", "Can Tho", "Nghe An", "Binh Dinh", "Hai Phong", "Lam Dong" }));
        diem_khoi_hanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diem_khoi_hanhActionPerformed(evt);
            }
        });

        label_ngay_di.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label_ngay_di.setForeground(new java.awt.Color(255, 255, 255));
        label_ngay_di.setText("Ngày đi:");

        label_khoi_hanh.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label_khoi_hanh.setForeground(new java.awt.Color(255, 255, 255));
        label_khoi_hanh.setText("Điểm khởi hành:");

        label_diem_den.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label_diem_den.setForeground(new java.awt.Color(255, 255, 255));
        label_diem_den.setText("Điểm đến:");

        ngay_di.setDateFormatString("dd/MM/yyyy");
        ngay_di.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        so_khach_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        label_ngay_di1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label_ngay_di1.setForeground(new java.awt.Color(255, 255, 255));
        label_ngay_di1.setText("Số hàng khách");

        javax.swing.GroupLayout khung_tim_chuyen_bayLayout = new javax.swing.GroupLayout(khung_tim_chuyen_bay);
        khung_tim_chuyen_bay.setLayout(khung_tim_chuyen_bayLayout);
        khung_tim_chuyen_bayLayout.setHorizontalGroup(
            khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mot_chieu)
                    .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                        .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_khoi_hanh)
                            .addComponent(diem_khoi_hanh, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diem_den, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_diem_den))
                        .addGap(58, 58, 58)
                        .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngay_di, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_ngay_di))
                        .addGap(75, 75, 75)
                        .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_ngay_di1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(so_khach_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                .addGap(485, 485, 485)
                .addComponent(nut_tim_chuyen_bay)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        khung_tim_chuyen_bayLayout.setVerticalGroup(
            khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(mot_chieu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_khoi_hanh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_diem_den)
                    .addComponent(label_ngay_di)
                    .addComponent(label_ngay_di1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(so_khach_combobox)
                    .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(diem_khoi_hanh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(diem_den, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ngay_di, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(nut_tim_chuyen_bay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnContainer1.add(khung_tim_chuyen_bay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 190));

        FlightScroll.setMaximumSize(new java.awt.Dimension(1200, 32767));

        FlightFoundedPane.setMaximumSize(new java.awt.Dimension(1200, 32767));

        javax.swing.GroupLayout FlightFoundedPaneLayout = new javax.swing.GroupLayout(FlightFoundedPane);
        FlightFoundedPane.setLayout(FlightFoundedPaneLayout);
        FlightFoundedPaneLayout.setHorizontalGroup(
            FlightFoundedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1194, Short.MAX_VALUE)
        );
        FlightFoundedPaneLayout.setVerticalGroup(
            FlightFoundedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        FlightScroll.setViewportView(FlightFoundedPane);

        pnContainer1.add(FlightScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1200, 560));

        javax.swing.GroupLayout cardDatVeLayout = new javax.swing.GroupLayout(cardDatVe);
        cardDatVe.setLayout(cardDatVeLayout);
        cardDatVeLayout.setHorizontalGroup(
            cardDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardDatVeLayout.setVerticalGroup(
            cardDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDatVeLayout.createSequentialGroup()
                .addComponent(pnContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jplMain.add(cardDatVe, "card4");

        cardHoSo.setPreferredSize(new java.awt.Dimension(1200, 750));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 750));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HỒ SƠ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(534, 534, 534)
                .addComponent(jLabel5)
                .addContainerGap(550, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(26, 26, 26))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel14.setText("EMAIL:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("MẬT KHẨU:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("TÊN ĐĂNG NHẬP:");

        ChangeMailButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ChangeMailButton.setText("SỬA");
        ChangeMailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    ChangeMailButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        ChangePasswordButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ChangePasswordButton.setText("ĐỔI MẬT KHẨU");
        ChangePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordButtonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 255, 255));
        jButton3.setText("Xóa Tài Khoản");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton3ActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        gmailField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gmailField.setText("DCMINH@GMAIL.COM");

        UserNameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UserNameField.setText("DCMINH");

        javax.swing.GroupLayout profImagePaneLayout = new javax.swing.GroupLayout(profImagePane);
        profImagePane.setLayout(profImagePaneLayout);
        profImagePaneLayout.setHorizontalGroup(
            profImagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        profImagePaneLayout.setVerticalGroup(
            profImagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ChangePasswordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ChangeMailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addComponent(profImagePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(profImagePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChangePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ChangeMailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout cardHoSoLayout = new javax.swing.GroupLayout(cardHoSo);
        cardHoSo.setLayout(cardHoSoLayout);
        cardHoSoLayout.setHorizontalGroup(
            cardHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardHoSoLayout.setVerticalGroup(
            cardHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jplMain.add(cardHoSo, "card5");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VÉ CỦA TÔI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(494, 494, 494))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MyTicketPaneLayout = new javax.swing.GroupLayout(MyTicketPane);
        MyTicketPane.setLayout(MyTicketPaneLayout);
        MyTicketPaneLayout.setHorizontalGroup(
            MyTicketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1182, Short.MAX_VALUE)
        );
        MyTicketPaneLayout.setVerticalGroup(
            MyTicketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        MyTicketScroll.setViewportView(MyTicketPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MyTicketScroll)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyTicketScroll)
                .addContainerGap())
        );

        javax.swing.GroupLayout cardVeCuaToiLayout = new javax.swing.GroupLayout(cardVeCuaToi);
        cardVeCuaToi.setLayout(cardVeCuaToiLayout);
        cardVeCuaToiLayout.setHorizontalGroup(
            cardVeCuaToiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardVeCuaToiLayout.setVerticalGroup(
            cardVeCuaToiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jplMain.add(cardVeCuaToi, "card5");

        pnContainer.add(jplMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMenuMouseClicked
        closeMenu();
    }//GEN-LAST:event_lblCloseMenuMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jplSlideMenu.setSize(0, y);
        x = 0;
    }//GEN-LAST:event_formWindowOpened

    private void lblTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseClicked
        cardTrangChu.setVisible(true);
        cardDatVe.setVisible(false);
        cardVeCuaToi.setVisible(false);
        cardHoSo.setVisible(false);
    }//GEN-LAST:event_lblTrangChuMouseClicked

    private void lblDatVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDatVeMouseClicked
        cardTrangChu.setVisible(false);
        cardDatVe.setVisible(true);
        cardVeCuaToi.setVisible(false);
        cardHoSo.setVisible(false);
    }//GEN-LAST:event_lblDatVeMouseClicked

    private void mot_chieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mot_chieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mot_chieuActionPerformed

    private void diem_khoi_hanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diem_khoi_hanhActionPerformed

    }//GEN-LAST:event_diem_khoi_hanhActionPerformed

    private void diem_denActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diem_denActionPerformed

    }//GEN-LAST:event_diem_denActionPerformed

    private void nut_tim_chuyen_bayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_tim_chuyen_bayActionPerformed

        FlightFoundedPane.removeAll();
        FlightFoundedPane.revalidate();
        FlightFoundedPane.repaint();

        String DerpatureAirport = diem_khoi_hanh.getSelectedItem().toString();
        String ArrivalAirport = diem_den.getSelectedItem().toString();
        Date DerpartureTime = ngay_di.getDate();
        int PassengerNumber = Integer.parseInt(so_khach_combobox.getSelectedItem().toString());

        ArrayList<Flightxtended> flightFounded = manager.flightControl.UserFindFlight(DerpartureTime, DerpatureAirport, ArrivalAirport, PassengerNumber);
        FlightFoundedPane.setLayout(new BoxLayout(FlightFoundedPane, BoxLayout.Y_AXIS));
        for (Flightxtended flight : flightFounded) {
            FlightTemplate tmp = new FlightTemplate(flight, PassengerNumber, userID);
            tmp.setPreferredSize(new Dimension(930, 240));
            tmp.setMaximumSize(new Dimension(1180, 240));
            tmp.setAlignmentX(Component.LEFT_ALIGNMENT); // Căn trái
            FlightFoundedPane.add(tmp);
        }
        FlightScroll.getVerticalScrollBar().setUnitIncrement(16);
        FlightFoundedPane.revalidate();
        FlightFoundedPane.repaint();
    }//GEN-LAST:event_nut_tim_chuyen_bayActionPerformed

    private void lblVeCuaToiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVeCuaToiMouseClicked
        cardTrangChu.setVisible(false);
        cardVeCuaToi.setVisible(true);
        cardDatVe.setVisible(false);
        cardHoSo.setVisible(false);
        loadMyTicketScroll();
    }//GEN-LAST:event_lblVeCuaToiMouseClicked

    private void loadMyTicketScroll() {
        MyTicketPane.removeAll();
        MyTicketScroll.setViewportView(MyTicketPane);
        MyTicketPane.setLayout(new BoxLayout(MyTicketPane, BoxLayout.Y_AXIS));
        ArrayList<Integer> passIDs = manager.reservationControl.getPassIDs(userID);
        for (int i : passIDs) {
            Ticket ticket = manager.reservationControl.getTicketByPassID(i);
            System.out.println(ticket);
            TicketTemplate t = new TicketTemplate(ticket, userID);
            t.setPreferredSize(new Dimension(1190, 390));
            t.setMaximumSize(new Dimension(1190, 390));
            t.setAlignmentX(Component.LEFT_ALIGNMENT);
            MyTicketPane.add(t);
            MyTicketPane.add(Box.createRigidArea(new Dimension(0, 10)));
        }
        MyTicketScroll.getVerticalScrollBar().setUnitIncrement(16);
        MyTicketPane.revalidate();
        MyTicketPane.repaint();
    }

    private void lblHoSoMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {//GEN-FIRST:event_lblHoSoMouseClicked
        cardTrangChu.setVisible(false);
        cardHoSo.setVisible(true);
        cardVeCuaToi.setVisible(false);
        cardDatVe.setVisible(false);
        loadProfileInfor();
    }//GEN-LAST:event_lblHoSoMouseClicked

    private void loadProfileInfor() throws SQLException {
        User user = Users.getUserByID(userID);
        UserNameField.setText(user.getAccount());
        gmailField.setText(user.getEmail());
        PasswordField.setText("*".repeat(user.getPassword().length()));

    }

    private void lbl_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuMouseClicked
        openMenu();
    }//GEN-LAST:event_lbl_menuMouseClicked

    private void label_dang_xuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_dang_xuatMouseClicked
        dispose();
        Login l = new Login();
        l.setVisible(true);
        l.pack();
        l.setLocationRelativeTo(null);
    }//GEN-LAST:event_label_dang_xuatMouseClicked

    private void ChangeMailButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_ChangeMailButtonActionPerformed

        ChangeEmail e = new ChangeEmail(this, gmailField.getText(), userID);
        e.setLocationRelativeTo(null);
        e.setVisible(true);
        gmailField.setText(e.getNewEmail());
    }//GEN-LAST:event_ChangeMailButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton3ActionPerformed

        String password = showDeleteAccountDialog();
        if (password != null) {
            if (manager.userControl.deleteUser(userID, password)) {
                JOptionPane.showMessageDialog(this, "Xóa tài khoản thành công!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                Login l = new Login();
                l.setVisible(true);
                l.pack();
                l.setLocationRelativeTo(null);
            } else {
                JOptionPane.showMessageDialog(null, "Mật khẩu không chính xác", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ChangePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordButtonActionPerformed

        ChangePasswordDialog P = new ChangePasswordDialog(this, userID);
        P.setLocationRelativeTo(null);
        P.setVisible(true);
        PasswordField.setText("*".repeat(P.getPWDlength()));
    }//GEN-LAST:event_ChangePasswordButtonActionPerformed

    private String showDeleteAccountDialog() {
        JPasswordField pwd = new JPasswordField();
        Object[] message = {
                "Enter your password: ", pwd
        };
        int option = JOptionPane.showConfirmDialog(
                this,
                message,
                "Xác nhận xóa tài khoản",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (option == JOptionPane.OK_OPTION) {
            return new String(pwd.getPassword());
        }
        return null;
    }
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeMailButton;
    private javax.swing.JButton ChangePasswordButton;
    private javax.swing.JPanel FlightFoundedPane;
    private javax.swing.JScrollPane FlightScroll;
    private javax.swing.JPanel HomePage;
    private javax.swing.JPanel MyTicketPane;
    private javax.swing.JScrollPane MyTicketScroll;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JLabel UserNameField;
    private javax.swing.JPanel cardDatVe;
    private javax.swing.JPanel cardHoSo;
    private javax.swing.JPanel cardTrangChu;
    private javax.swing.JPanel cardVeCuaToi;
    private javax.swing.JPanel container_avatar_close;
    private javax.swing.JComboBox<String> diem_den;
    private javax.swing.JComboBox<String> diem_khoi_hanh;
    private javax.swing.JLabel gmailField;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jplMain;
    private javax.swing.JPanel jplSlideMenu;
    private javax.swing.JPanel khung_tim_chuyen_bay;
    private javax.swing.JLabel label_dang_xuat;
    private javax.swing.JLabel label_diem_den;
    private javax.swing.JLabel label_khoi_hanh;
    private javax.swing.JLabel label_ngay_di;
    private javax.swing.JLabel label_ngay_di1;
    private javax.swing.JLabel lblCloseMenu;
    private javax.swing.JLabel lblDatVe;
    private javax.swing.JLabel lblHoSo;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JLabel lblVeCuaToi;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JRadioButton mot_chieu;
    private com.toedter.calendar.JDateChooser ngay_di;
    private javax.swing.JButton nut_tim_chuyen_bay;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnContainer1;
    private javax.swing.JPanel profImagePane;
    private javax.swing.JComboBox<String> so_khach_combobox;
    private javax.swing.JPanel thanh_menu;
    // End of variables declaration//GEN-END:variables
}
