/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.main;

/**
 *
 * @author ADMIN
 */
public class Ticket extends javax.swing.JPanel {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTicket = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        pnTitle = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        pnBorder = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_passenger_name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_from = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_to = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_flight = new javax.swing.JLabel();
        lbl_board_till = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_to1 = new javax.swing.JLabel();
        lbl_seat = new javax.swing.JLabel();
        lbl_gate = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbl_gate1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lbl_from1 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lbl_passenger_name1 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        lbl_date1 = new javax.swing.JLabel();
        lbl_time1 = new javax.swing.JLabel();
        lbl_flight1 = new javax.swing.JLabel();
        lbl_seat1 = new javax.swing.JLabel();

        pnTicket.setBackground(new java.awt.Color(255, 255, 255));
        pnTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnTicket.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 1, 10, 300));

        pnTitle.setBackground(new java.awt.Color(204, 0, 0));

        jLabel27.setFont(new java.awt.Font("Segoe UI Historic", 0, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("CLC04 AirLines");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/logoticket.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Boarding pass");

        jLabel30.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("ECONOMY");

        jLabel31.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Boarding pass");

        jLabel32.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("ECONOMY");

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(231, 231, 231)
                .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30))
                .addGap(19, 19, 19))
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32)))
                    .addComponent(jLabel29)
                    .addGroup(pnTitleLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel27)))
                .addContainerGap())
        );

        pnTicket.add(pnTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        pnBorder.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout pnBorderLayout = new javax.swing.GroupLayout(pnBorder);
        pnBorder.setLayout(pnBorderLayout);
        pnBorderLayout.setHorizontalGroup(
            pnBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnBorderLayout.setVerticalGroup(
            pnBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnTicket.add(pnBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 283, 1200, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Passenger name:");
        pnTicket.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, -1, -1));

        lbl_passenger_name.setText("jLabel6");
        pnTicket.add(lbl_passenger_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 153, 118, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setText("From:");
        pnTicket.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 55, 20));

        lbl_from.setText("jLabel6");
        pnTicket.add(lbl_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 200, 118, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel9.setText("To:");
        pnTicket.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 49, -1));

        lbl_to.setText("jLabel6");
        pnTicket.add(lbl_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 247, 118, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel14.setText("Date:");
        pnTicket.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, 43, -1));

        lbl_date.setText("jLabel6");
        pnTicket.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 153, 135, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel16.setText("Flight:");
        pnTicket.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel18.setText("Gate:");
        pnTicket.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, -1, -1));

        lbl_flight.setText("jLabel6");
        pnTicket.add(lbl_flight, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 200, 135, -1));

        lbl_board_till.setText("jLabel6");
        pnTicket.add(lbl_board_till, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 247, 131, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel21.setText("Seat:");
        pnTicket.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 170, 43, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel22.setText("Time:");
        pnTicket.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 130, 43, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel23.setText("Board till:");
        pnTicket.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 222, -1, -1));

        lbl_to1.setText("jLabel6");
        pnTicket.add(lbl_to1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 131, 20));

        lbl_seat.setText("jLabel6");
        pnTicket.add(lbl_seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 200, 131, -1));

        lbl_gate.setText("jLabel6");
        pnTicket.add(lbl_gate, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 247, 135, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel33.setText("Passenger name:");
        pnTicket.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 128, -1, -1));

        lbl_time.setText("jLabel6");
        pnTicket.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 153, 131, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel35.setText("From:");
        pnTicket.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 175, 55, -1));

        lbl_gate1.setText("jLabel6");
        pnTicket.add(lbl_gate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, 50, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel37.setText("To:");
        pnTicket.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 222, 49, -1));

        lbl_from1.setText("jLabel6");
        pnTicket.add(lbl_from1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 131, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel39.setText("Date:");
        pnTicket.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 128, 43, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel40.setText("Time:");
        pnTicket.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 128, 43, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel41.setText("Flight:");
        pnTicket.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 175, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel42.setText("Seat:");
        pnTicket.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 175, 43, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel43.setText("Gate:");
        pnTicket.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 222, -1, -1));

        lbl_passenger_name1.setText("jLabel6");
        pnTicket.add(lbl_passenger_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 120, -1));

        jLabel45.setText("jLabel6");
        pnTicket.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 131, -1));

        lbl_date1.setText("jLabel6");
        pnTicket.add(lbl_date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 150, 50, -1));

        lbl_time1.setText("jLabel6");
        pnTicket.add(lbl_time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 150, 50, -1));

        lbl_flight1.setText("jLabel6");
        pnTicket.add(lbl_flight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, 50, -1));

        lbl_seat1.setText("jLabel6");
        pnTicket.add(lbl_seat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 190, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_board_till;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_date1;
    private javax.swing.JLabel lbl_flight;
    private javax.swing.JLabel lbl_flight1;
    private javax.swing.JLabel lbl_from;
    private javax.swing.JLabel lbl_from1;
    private javax.swing.JLabel lbl_gate;
    private javax.swing.JLabel lbl_gate1;
    private javax.swing.JLabel lbl_passenger_name;
    private javax.swing.JLabel lbl_passenger_name1;
    private javax.swing.JLabel lbl_seat;
    private javax.swing.JLabel lbl_seat1;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_time1;
    private javax.swing.JLabel lbl_to;
    private javax.swing.JLabel lbl_to1;
    private javax.swing.JPanel pnBorder;
    private javax.swing.JPanel pnTicket;
    private javax.swing.JPanel pnTitle;
    // End of variables declaration//GEN-END:variables
}
