/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.CardLayout;



/**
 *
 * @author ADMIN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        button_adminlogin = new javax.swing.JButton();
        button_signup = new javax.swing.JButton();
        button_login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        khung_tim_chuyen_bay = new javax.swing.JPanel();
        mot_chieu = new javax.swing.JRadioButton();
        khu_hoi = new javax.swing.JRadioButton();
        tien_te = new javax.swing.JLabel();
        diem_den = new javax.swing.JComboBox<>();
        nut_tim_chuyen_bay = new javax.swing.JButton();
        diem_khoi_hanh = new javax.swing.JComboBox<>();
        label_ngay_di = new javax.swing.JLabel();
        label_khoi_hanh = new javax.swing.JLabel();
        label_diem_den = new javax.swing.JLabel();
        chon_ngay_di = new com.toedter.calendar.JDateChooser();
        anh_may_hong = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        BrandName = new javax.swing.JLabel();
        CopyRight = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        SignUpButtons = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Button_back_login = new javax.swing.JButton();
        SignUp = new javax.swing.JPanel();
        Left1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BrandName1 = new javax.swing.JLabel();
        CopyRight1 = new javax.swing.JLabel();
        label_logo = new javax.swing.JLabel();
        Right1 = new javax.swing.JPanel();
        SignUpLabel = new javax.swing.JLabel();
        Fullname = new javax.swing.JLabel();
        FullnameField = new javax.swing.JTextField();
        EmailField1 = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        PasswordField1 = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        LoginButton1 = new javax.swing.JButton();
        Button_back_signup = new javax.swing.JButton();
        AdminLogin = new javax.swing.JPanel();
        Left2 = new javax.swing.JPanel();
        BrandName2 = new javax.swing.JLabel();
        CopyRight2 = new javax.swing.JLabel();
        adminlogo = new javax.swing.JLabel();
        Right2 = new javax.swing.JPanel();
        LoginLabel1 = new javax.swing.JLabel();
        EmailLabel1 = new javax.swing.JLabel();
        EmailField2 = new javax.swing.JTextField();
        PasswordLabel1 = new javax.swing.JLabel();
        PasswordField2 = new javax.swing.JPasswordField();
        LoginButton2 = new javax.swing.JButton();
        button_back_adminlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME\n");
        getContentPane().setLayout(new java.awt.CardLayout());

        background.setLayout(null);

        button_adminlogin.setBackground(new java.awt.Color(204, 0, 0));
        button_adminlogin.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        button_adminlogin.setForeground(new java.awt.Color(255, 255, 255));
        button_adminlogin.setText("AdminLogin");
        button_adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_adminloginActionPerformed(evt);
            }
        });
        background.add(button_adminlogin);
        button_adminlogin.setBounds(750, 10, 110, 30);

        button_signup.setBackground(new java.awt.Color(204, 0, 0));
        button_signup.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        button_signup.setForeground(new java.awt.Color(255, 255, 255));
        button_signup.setText("SignUp");
        button_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signupActionPerformed(evt);
            }
        });
        background.add(button_signup);
        button_signup.setBounds(660, 10, 80, 30);

        button_login.setBackground(new java.awt.Color(204, 0, 0));
        button_login.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        button_login.setForeground(new java.awt.Color(255, 255, 255));
        button_login.setText("Login");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });
        background.add(button_login);
        button_login.setBounds(570, 10, 75, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login.png"))); // NOI18N
        background.add(jLabel2);
        jLabel2.setBounds(540, 10, 30, 30);

        khung_tim_chuyen_bay.setBackground(new java.awt.Color(204, 0, 0));
        khung_tim_chuyen_bay.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        mot_chieu.setBackground(new java.awt.Color(204, 0, 0));
        mot_chieu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        mot_chieu.setForeground(new java.awt.Color(255, 255, 255));
        mot_chieu.setText("Một chiều");
        mot_chieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mot_chieuActionPerformed(evt);
            }
        });

        khu_hoi.setBackground(new java.awt.Color(204, 0, 0));
        khu_hoi.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        khu_hoi.setForeground(new java.awt.Color(255, 255, 255));
        khu_hoi.setText("Khứ hồi");

        tien_te.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        tien_te.setForeground(new java.awt.Color(255, 255, 255));
        tien_te.setText("VND");

        diem_den.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        diem_den.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội (HAN), Việt Nam", "Tp. Hồ Chí Minh (SGN), Việt Nam", "Đà Nẵng (DAD), Việt Nam", "Phú Quốc (PQC), Việt Nam", "Nha Trang (CXR), Việt Nam", "Buôn Ma Thuột (BMV), Việt Nam", "Cà Mau (CAH), Việt Nam", "Cần Thơ (VCA), Việt Nam", "Chu Lai (VCL), Việt Nam", "Côn Đảo (VCS), Việt Nam", "Đà Lạt (DLI), Việt Nam", "Điện Biên (DIN), Việt Nam", "Đồng Hới (VDH), Việt Nam", "Hải Phòng (HPH), Việt Nam", "Huế (HUI), Việt Nam", "Pleiku (PXU), Việt Nam", "Quy Nhơn (UIH), Việt Nam", "Rạch Giá (VKG), Việt Nam", "Thanh Hóa (THD), Việt Nam", "Tuy Hòa (TBB), Việt Nam", "Vân Đồn (VDO), Việt Nam", "Vinh (VII), Việt Nam", " " }));

        nut_tim_chuyen_bay.setBackground(new java.awt.Color(255, 255, 0));
        nut_tim_chuyen_bay.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        nut_tim_chuyen_bay.setText("Tìm chuyến bay");

        diem_khoi_hanh.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        diem_khoi_hanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội (HAN), Việt Nam", "Tp. Hồ Chí Minh (SGN), Việt Nam", "Đà Nẵng (DAD), Việt Nam", "Phú Quốc (PQC), Việt Nam", "Nha Trang (CXR), Việt Nam", "Buôn Ma Thuột (BMV), Việt Nam", "Cà Mau (CAH), Việt Nam", "Cần Thơ (VCA), Việt Nam", "Chu Lai (VCL), Việt Nam", "Côn Đảo (VCS), Việt Nam", "Đà Lạt (DLI), Việt Nam", "Điện Biên (DIN), Việt Nam", "Đồng Hới (VDH), Việt Nam", "Hải Phòng (HPH), Việt Nam", "Huế (HUI), Việt Nam", "Pleiku (PXU), Việt Nam", "Quy Nhơn (UIH), Việt Nam", "Rạch Giá (VKG), Việt Nam", "Thanh Hóa (THD), Việt Nam", "Tuy Hòa (TBB), Việt Nam", "Vân Đồn (VDO), Việt Nam", "Vinh (VII), Việt Nam", " " }));
        diem_khoi_hanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diem_khoi_hanhActionPerformed(evt);
            }
        });

        label_ngay_di.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        label_ngay_di.setForeground(new java.awt.Color(255, 255, 255));
        label_ngay_di.setText("Ngày đi:");

        label_khoi_hanh.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        label_khoi_hanh.setForeground(new java.awt.Color(255, 255, 255));
        label_khoi_hanh.setText("Điểm khởi hành:");

        label_diem_den.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        label_diem_den.setForeground(new java.awt.Color(255, 255, 255));
        label_diem_den.setText("Điểm đến:");

        chon_ngay_di.setDateFormatString("dd/MM/yyyy");
        chon_ngay_di.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout khung_tim_chuyen_bayLayout = new javax.swing.GroupLayout(khung_tim_chuyen_bay);
        khung_tim_chuyen_bay.setLayout(khung_tim_chuyen_bayLayout);
        khung_tim_chuyen_bayLayout.setHorizontalGroup(
            khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chon_ngay_di, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diem_khoi_hanh, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diem_den, 0, 306, Short.MAX_VALUE)
                    .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                        .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_diem_den)
                            .addComponent(label_ngay_di)
                            .addComponent(label_khoi_hanh))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                        .addComponent(mot_chieu)
                        .addGap(33, 33, 33)
                        .addComponent(khu_hoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tien_te)))
                .addContainerGap())
            .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(nut_tim_chuyen_bay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        khung_tim_chuyen_bayLayout.setVerticalGroup(
            khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khung_tim_chuyen_bayLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(khung_tim_chuyen_bayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mot_chieu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khu_hoi)
                    .addComponent(tien_te))
                .addGap(18, 18, 18)
                .addComponent(label_khoi_hanh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diem_khoi_hanh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_diem_den)
                .addGap(11, 11, 11)
                .addComponent(diem_den, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_ngay_di)
                .addGap(18, 18, 18)
                .addComponent(chon_ngay_di, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nut_tim_chuyen_bay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        background.add(khung_tim_chuyen_bay);
        khung_tim_chuyen_bay.setBounds(540, 50, 320, 390);

        anh_may_hong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bg.jpg"))); // NOI18N
        background.add(anh_may_hong);
        anh_may_hong.setBounds(0, 0, 900, 500);

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        getContentPane().add(Home, "home");

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setPreferredSize(new java.awt.Dimension(896, 497));
        Login.setLayout(null);

        Left.setBackground(new java.awt.Color(204, 0, 0));
        Left.setPreferredSize(new java.awt.Dimension(400, 500));

        BrandName.setFont(new java.awt.Font("Showcard Gothic", 3, 36)); // NOI18N
        BrandName.setForeground(new java.awt.Color(255, 255, 255));
        BrandName.setText("CLC04 Airlines");

        CopyRight.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        CopyRight.setForeground(new java.awt.Color(255, 255, 255));
        CopyRight.setText("copyright (c) CLC04 AIRLINES All rights reversed");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logo.png"))); // NOI18N
        logo.setText("jLabel1");

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CopyRight)
                    .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(93, 93, 93))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                            .addComponent(BrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)))))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(BrandName)
                .addGap(91, 91, 91)
                .addComponent(CopyRight)
                .addGap(106, 106, 106))
        );

        Login.add(Left);
        Left.setBounds(0, 0, 450, 500);

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(204, 0, 0));
        LoginLabel.setText("LOGIN");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        EmailLabel.setText("Email");

        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PasswordLabel.setText("Password");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        SignUpButtons.setBackground(new java.awt.Color(204, 204, 204));
        SignUpButtons.setText("Sign Up");
        SignUpButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("I don't have a acccount");

        LoginButton.setBackground(new java.awt.Color(204, 0, 0));
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        Button_back_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        Button_back_login.setPreferredSize(new java.awt.Dimension(40, 35));
        Button_back_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_back_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(LoginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_back_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginButton)
                    .addComponent(PasswordLabel)
                    .addComponent(EmailLabel)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(RightLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SignUpButtons))))
                .addGap(76, 76, 76))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Button_back_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(EmailLabel)
                .addGap(18, 18, 18)
                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(SignUpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        Login.add(Right);
        Right.setBounds(450, 0, 450, 500);

        getContentPane().add(Login, "login");

        SignUp.setBackground(new java.awt.Color(255, 255, 255));
        SignUp.setPreferredSize(new java.awt.Dimension(896, 497));
        SignUp.setLayout(null);

        Left1.setBackground(new java.awt.Color(204, 0, 0));
        Left1.setMinimumSize(new java.awt.Dimension(400, 500));

        BrandName1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        BrandName1.setForeground(new java.awt.Color(255, 255, 255));
        BrandName1.setText("CLC04 Airlines");

        CopyRight1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        CopyRight1.setForeground(new java.awt.Color(255, 255, 255));
        CopyRight1.setText("copyright (c) CLC04 AIRLINES All rights reserved");

        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout Left1Layout = new javax.swing.GroupLayout(Left1);
        Left1.setLayout(Left1Layout);
        Left1Layout.setHorizontalGroup(
            Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(label_logo)
                .addGap(128, 128, 128)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Left1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CopyRight1)
                    .addComponent(BrandName1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        Left1Layout.setVerticalGroup(
            Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left1Layout.createSequentialGroup()
                .addGroup(Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Left1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Logo))
                    .addGroup(Left1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(label_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(BrandName1)
                .addGap(80, 80, 80)
                .addComponent(CopyRight1)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        SignUp.add(Left1);
        Left1.setBounds(0, 0, 470, 500);

        Right1.setBackground(new java.awt.Color(255, 255, 255));

        SignUpLabel.setBackground(new java.awt.Color(255, 255, 255));
        SignUpLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        SignUpLabel.setForeground(new java.awt.Color(204, 0, 0));
        SignUpLabel.setText("Sign Up");

        Fullname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Fullname.setText("Full name");

        FullnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullnameFieldActionPerformed(evt);
            }
        });

        EmailField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailField1ActionPerformed(evt);
            }
        });

        Email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Email.setText("Email");

        Password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Password.setText("Password");

        SignUpButton.setBackground(new java.awt.Color(204, 0, 0));
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("Sign Up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("I've an account");

        LoginButton1.setBackground(new java.awt.Color(204, 204, 204));
        LoginButton1.setText("Login");
        LoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButton1ActionPerformed(evt);
            }
        });

        Button_back_signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        Button_back_signup.setPreferredSize(new java.awt.Dimension(40, 35));
        Button_back_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_back_signupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Right1Layout = new javax.swing.GroupLayout(Right1);
        Right1.setLayout(Right1Layout);
        Right1Layout.setHorizontalGroup(
            Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignUpLabel)
                .addGap(105, 105, 105)
                .addComponent(Button_back_signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Right1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password)
                    .addComponent(Email)
                    .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Fullname)
                        .addComponent(FullnameField)
                        .addComponent(PasswordField1)
                        .addComponent(EmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Right1Layout.createSequentialGroup()
                            .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SignUpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        Right1Layout.setVerticalGroup(
            Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right1Layout.createSequentialGroup()
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Right1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(SignUpLabel))
                    .addComponent(Button_back_signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Fullname)
                .addGap(9, 9, 9)
                .addComponent(EmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FullnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        SignUp.add(Right1);
        Right1.setBounds(470, 0, 430, 500);

        getContentPane().add(SignUp, "signup");

        AdminLogin.setBackground(new java.awt.Color(255, 255, 255));
        AdminLogin.setPreferredSize(new java.awt.Dimension(896, 497));
        AdminLogin.setLayout(null);

        Left2.setBackground(new java.awt.Color(204, 0, 0));
        Left2.setPreferredSize(new java.awt.Dimension(400, 500));

        BrandName2.setFont(new java.awt.Font("Showcard Gothic", 3, 36)); // NOI18N
        BrandName2.setForeground(new java.awt.Color(255, 255, 255));
        BrandName2.setText("CLC04 Airlines");

        CopyRight2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        CopyRight2.setForeground(new java.awt.Color(255, 255, 255));
        CopyRight2.setText("copyright (c) CLC04 AIRLINES All rights reversed");

        adminlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/admin.png"))); // NOI18N
        adminlogo.setText("jLabel1");

        javax.swing.GroupLayout Left2Layout = new javax.swing.GroupLayout(Left2);
        Left2.setLayout(Left2Layout);
        Left2Layout.setHorizontalGroup(
            Left2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Left2Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(Left2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Left2Layout.createSequentialGroup()
                        .addComponent(adminlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Left2Layout.createSequentialGroup()
                        .addGroup(Left2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CopyRight2)
                            .addComponent(BrandName2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))))
        );
        Left2Layout.setVerticalGroup(
            Left2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(adminlogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BrandName2)
                .addGap(47, 47, 47)
                .addComponent(CopyRight2)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        AdminLogin.add(Left2);
        Left2.setBounds(0, 0, 450, 500);

        Right2.setBackground(new java.awt.Color(255, 255, 255));
        Right2.setPreferredSize(new java.awt.Dimension(400, 500));

        LoginLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LoginLabel1.setForeground(new java.awt.Color(204, 0, 0));
        LoginLabel1.setText("ADMIN LOGIN");

        EmailLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        EmailLabel1.setText("Email");

        EmailField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailField2ActionPerformed(evt);
            }
        });

        PasswordLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PasswordLabel1.setText("Password");

        PasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField2ActionPerformed(evt);
            }
        });

        LoginButton2.setBackground(new java.awt.Color(204, 0, 0));
        LoginButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LoginButton2.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton2.setText("Login");
        LoginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButton2ActionPerformed(evt);
            }
        });

        button_back_adminlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        button_back_adminlogin.setPreferredSize(new java.awt.Dimension(40, 35));
        button_back_adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_back_adminloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Right2Layout = new javax.swing.GroupLayout(Right2);
        Right2.setLayout(Right2Layout);
        Right2Layout.setHorizontalGroup(
            Right2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(LoginButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right2Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(Right2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right2Layout.createSequentialGroup()
                        .addGroup(Right2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordLabel1)
                            .addComponent(EmailLabel1)
                            .addComponent(EmailField2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right2Layout.createSequentialGroup()
                        .addComponent(LoginLabel1)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right2Layout.createSequentialGroup()
                        .addComponent(button_back_adminlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        Right2Layout.setVerticalGroup(
            Right2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right2Layout.createSequentialGroup()
                .addComponent(button_back_adminlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(LoginLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(EmailLabel1)
                .addGap(18, 18, 18)
                .addComponent(EmailField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(PasswordLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(LoginButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        AdminLogin.add(Right2);
        Right2.setBounds(440, 0, 460, 500);

        getContentPane().add(AdminLogin, "adminlogin");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diem_khoi_hanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diem_khoi_hanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diem_khoi_hanhActionPerformed

    private void mot_chieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mot_chieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mot_chieuActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void SignUpButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonsActionPerformed
        showPanel("signup");
    }//GEN-LAST:event_SignUpButtonsActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void FullnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullnameFieldActionPerformed

    private void EmailField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailField1ActionPerformed

    private void LoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButton1ActionPerformed
        showPanel("login");
    }//GEN-LAST:event_LoginButton1ActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void Button_back_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_back_signupActionPerformed
        showPanel("home");
    }//GEN-LAST:event_Button_back_signupActionPerformed

    private void EmailField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailField2ActionPerformed

    private void PasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField2ActionPerformed

    private void LoginButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButton2ActionPerformed

    private void button_back_adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_back_adminloginActionPerformed
        showPanel("home");
    }//GEN-LAST:event_button_back_adminloginActionPerformed

    private void Button_back_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_back_loginActionPerformed
        showPanel("home");
    }//GEN-LAST:event_Button_back_loginActionPerformed

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        showPanel("login");
    }//GEN-LAST:event_button_loginActionPerformed

    private void button_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signupActionPerformed
        showPanel("signup");
    }//GEN-LAST:event_button_signupActionPerformed

    private void button_adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_adminloginActionPerformed
        showPanel("adminlogin");
    }//GEN-LAST:event_button_adminloginActionPerformed

    private void showPanel(String panelName) {                                                
       CardLayout layout = (CardLayout) getContentPane().getLayout();
        layout.show(getContentPane(), panelName);
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminLogin;
    private javax.swing.JLabel BrandName;
    private javax.swing.JLabel BrandName1;
    private javax.swing.JLabel BrandName2;
    private javax.swing.JButton Button_back_login;
    private javax.swing.JButton Button_back_signup;
    private javax.swing.JLabel CopyRight;
    private javax.swing.JLabel CopyRight1;
    private javax.swing.JLabel CopyRight2;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField EmailField1;
    private javax.swing.JTextField EmailField2;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel EmailLabel1;
    private javax.swing.JLabel Fullname;
    private javax.swing.JTextField FullnameField;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Left1;
    private javax.swing.JPanel Left2;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton LoginButton1;
    private javax.swing.JButton LoginButton2;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel LoginLabel1;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JPasswordField PasswordField2;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel Right1;
    private javax.swing.JPanel Right2;
    private javax.swing.JPanel SignUp;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JButton SignUpButtons;
    private javax.swing.JLabel SignUpLabel;
    private javax.swing.JLabel adminlogo;
    private javax.swing.JLabel anh_may_hong;
    private javax.swing.JPanel background;
    private javax.swing.JButton button_adminlogin;
    private javax.swing.JButton button_back_adminlogin;
    private javax.swing.JButton button_login;
    private javax.swing.JButton button_signup;
    private com.toedter.calendar.JDateChooser chon_ngay_di;
    private javax.swing.JComboBox<String> diem_den;
    private javax.swing.JComboBox<String> diem_khoi_hanh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton khu_hoi;
    private javax.swing.JPanel khung_tim_chuyen_bay;
    private javax.swing.JLabel label_diem_den;
    private javax.swing.JLabel label_khoi_hanh;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_ngay_di;
    private javax.swing.JLabel logo;
    private javax.swing.JRadioButton mot_chieu;
    private javax.swing.JButton nut_tim_chuyen_bay;
    private javax.swing.JLabel tien_te;
    // End of variables declaration//GEN-END:variables
}
